global:
  scrape_interval: 5s

scrape_configs:
  - job_name: local-demo
    static_configs:
      - targets:
          - localhost:9090
        labels:
          tenant: team-a
          cluster: eu-1
          environment: production
      - targets:
          - localhost:9090
        labels:
          tenant: team-b
          cluster: us-1
          environment: staging
